<?php
/**
 * Created by PhpStorm.
 * User: Ivan
 * Date: 08.02.2015
 * Time: 14:01
 */
echo('index Brands');

$title = 'My brands';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('brands', array('action' => 'add'));?>">Add new album</a>
</p>

<table class="table">
    <tr>
        <th>Name</th>

        <th>&nbsp;</th>
    </tr>

    <?php foreach ($brands as $brand) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($brand->name);?></td>

            <td>
                <a href="<?php echo $this->url('brands',
                    array('action'=>'edit', 'id' => $brand->id));?>">Edit</a>
                <a href="<?php echo $this->url('brands',
                    array('action'=>'delete', 'id' => $brand->id));?>">Delete</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>